Add Pulsar Community Weekly Update - 2021-06-21~ 2021-06-27
streamnative/pulsar_weekly pull request #105
Opened 2021-06-29 10:08 UTC by Huanli-Meng

2021-06-29 13:18 UTC, BewareMyPower requested changes

2021-06-29 13:18 UTC, BewareMyPower commented on content/2021/2021-06/2021-06-28-pulsar-weekly.md
> +    https://github.com/apache/pulsar/pull/10983 ([[@newur](https://github.com/newur))
```suggestion
    https://github.com/apache/pulsar/pull/10983 ([@newur](https://github.com/newur))
```

2021-06-29 13:23 UTC, BewareMyPower approved these changes

2021-06-30 02:27 UTC, Jennifer88huang commented on content/2021/2021-06/2021-06-28-pulsar-weekly.md
> +    - https://streamnative.io/en/blog/community/2021-06-22-highlights-from-the-pulsar-virtual-summit-north-america-2021
It's good to include StreamNative blogs, if there are more good quality blogs from the Pulsar community, please also include them to show diversity.

2021-06-30 02:27 UTC, Jennifer88huang commented on content/2021/2021-06/2021-06-28-pulsar-weekly.md
> +- [TGIP] Weekly live stream about Pulsar and its ecosystem.
There will be big changes to TGIP name and episodes soon, you can add it below other impactful events in the future.
For example, you can introduce Pulsar 101 first and then TGIP.

2021-06-30 02:46 UTC, Anonymitaet approved these changes

2021-06-30 02:46 UTC, Anonymitaet commented on content/2021/2021-06/2021-06-28-pulsar-weekly.md
> +- [Build] Fix the compilation error caused by the the number of incorrect parameters.
```suggestion
- [Build] Fix the compilation error caused by the number of incorrect parameters.
```

2021-06-30 05:51 UTC, merged